// JavaScript Document
var gamelist = { 

            'bonus_slot':[ 
                  { "GameID":"59065","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_108Heroes.jpg","title":"108好汉"}, 
                  { "GameID":"59067","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_3Empire_ZH.jpg","title":"三國"}, 
                  { "GameID":"28136","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_AgeofDiscovery3.jpg","title":"大航海时代"},
				  { "GameID":"28148","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_AlaxeInZombieland.jpg","title":"亚历山大在尸乐园"},
				  { "GameID":"28166","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_ArcticFortune1.jpg","title":"极寒鸿运"},
				  { "GameID":"28182","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_AroundTheWorld.jpg","title":"环游世界"},
				  { "GameID":"28198","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_AvalonII.jpg","title":"阿瓦隆2"},
				  { "GameID":"28266","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_BigBreak1.jpg","title":"大破"},
				  { "GameID":"28270","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_BigKahuna1.jpg","title":"征服钱海"},
				  { "GameID":"46497","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_BikiniParty_ZH.jpg","title":"比基尼派对"},
				  { "GameID":"28286","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_BootyTime.jpg","title":"藏宝时间"},
				  { "GameID":"29601","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_BrideZilla.jpg","title":"新娘吉拉"},
				  { "GameID":"28336","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_BushTelegraph1.jpg","title":"丛林摇摆 "},
				  { "GameID":"29555","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_BustTheBank1.jpg","title":"抢劫银行"},
				  { "GameID":"28364","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Cashanova1.jpg","title":"卡萨努瓦"},
				  /*{ "GameID":"28376","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/","title":"挥金如土"},*/
				  { "GameID":"28476","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_DinoMight1.jpg","title":"恐龙迪诺"},
				  { "GameID":"28480","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Dogfather2.jpg","title":"狗爸爸"},
				  { "GameID":"28484","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_DolphinQuest.jpg","title":"寻访海豚"},
				  { "GameID":"28522","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_DrWattsUp1.jpg","title":"恐怖实验室"},
				  { "GameID":"46494","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_DragonDance_ZH.jpg","title":"舞龙"},
				  { "GameID":"28542","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_DroneWars.jpg","title":"熊峰战争"},
				  { "GameID":"28562","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_EaglesWings1.jpg","title":"老鹰的翅膀"},
				  { "GameID":"61497","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_ElectricDiva_zh.jpg","title":"雷电歌后"},
				  { "GameID":"28592","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_footballstar1.jpg","title":"足球明星"},
				  { "GameID":"66080","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_FrozenDiamonds.jpg","title":"急冻钻石"},
				  { "GameID":"28618","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_GiftRap2.jpg","title":"礼品包装"},
				  { "GameID":"29449","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_GirlswithGuns2.jpg","title":"女孩与枪II"},
				  { "GameID":"28622","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_GirlswithGuns1.jpg","title":"女孩与枪"},
				  { "GameID":"28648","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Halloweenies1.jpg","title":"万圣节"},
				  { "GameID":"28500","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_HellBoy1.jpg","title":"地狱男爵"},
				  { "GameID":"28502","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_HellGrannies.jpg","title":"地狱阿嬷"},
				  { "GameID":"28516","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_HighSociety.jpg","title":"上流社会"},
				  { "GameID":"28670","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Hitman1.jpg","title":"终极杀手"},
				  { "GameID":"28680","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_HouseofDragons.jpg","title":"龙之家"},
				  { "GameID":"28660","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_JekyllandHyde.jpg","title":"判若两人"},
				  { "GameID":"28652","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_JewelsoftheOrient1.jpg","title":"东方珠宝"},
				  { "GameID":"28744","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_KingArthur.jpg","title":"亚瑟王"},
				  { "GameID":"28780","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_LeaguesOfFortune1.jpg","title":"财富阶级"},
				  { "GameID":"28790","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Loaded1.jpg","title":"炫富一族"},
				  { "GameID":"28796","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_LooseCannon1.jpg","title":"海盗王"},
				 /* { "GameID":"28794","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/","title":"幸运的锦鲤"},*/
				  { "GameID":"28782","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_LuckyLeprechaunsLoot.jpg","title":"妖精的战利品"},
				  { "GameID":"28766","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_MadHatters1.jpg","title":"疯狂的帽子"},
				  { "GameID":"28716","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_MermaidsMillions1.jpg","title":"海底世界"},
				  { "GameID":"28712","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_MoneyMadMonkey1.jpg","title":"疯狂的猴子"},
				  { "GameID":"28708","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Moonshine1.jpg","title":"月光"},
				  { "GameID":"28676","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_MountOlympus.jpg","title":"奥林匹斯山"},
				  { "GameID":"28600","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_MysticDreams1.jpg","title":"神秘梦境 "},
				  { "GameID":"28578","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_MystiqueGrove.jpg","title":"神秘森林"},
				  { "GameID":"61149","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_NinjaMagic_zh.jpg","title":"忍者法宝"},
				  { "GameID":"28560","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_ParadiseFound.jpg","title":"发现天堂"},
				  { "GameID":"28570","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_PhantomCash.jpg","title":"幻影现金"},
				  { "GameID":"28556","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_PiggyFortunes.jpg","title":"小猪财富"},
				  { "GameID":"28858","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Playboy1.jpg","title":"花花公子"},
				  { "GameID":"28890","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_PollenNation1.jpg","title":"蜜蜂乐园"},
				  { "GameID":"61147","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_prettykitty_zh.jpg","title":"漂亮猫咪"},
				  { "GameID":"28910","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_PrimeProperty1.jpg","title":"优质物业"},
				  { "GameID":"28496","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_RacingForPinks.jpg","title":"为粉红而战"},
				  { "GameID":"28440","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_robojack1.jpg","title":"洛伯杰克"},
				  { "GameID":"28434","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_RollerDerby.jpg","title":"滚德比"},
				  { "GameID":"28416","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SantasWildRide1.jpg","title":"圣诞老人的疯狂 ？"},
				  { "GameID":"28406","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SecretSanta.jpg","title":"圣诞老人的秘密"},
				  { "GameID":"28402","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Shoot.jpg","title":"射击"},
				  { "GameID":"28392","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SkullDuggery1.jpg","title":"骷髅陷阱"},
				  { "GameID":"28378","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SoccerSafari1.jpg","title":"动物足球"},
				  { "GameID":"28344","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_StarlightKiss.jpg","title":"星梦之吻"},
				  { "GameID":"28342","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_StarScape1.jpg","title":"星云"},
				  { "GameID":"28338","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SteamPunkHeroes.jpg","title":"蒸汽朋克英雄"},
				  { "GameID":"28334","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SterlingSilver3D1.jpg","title":"纯银3D"},
				  { "GameID":"50193","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SunTide_Button_ZH.jpg","title":"太阳征程"},
				  { "GameID":"28314","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_SurfSafari.jpg","title":"动物冲浪"},
				  { "GameID":"28300","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_Terminator2_1.jpg","title":"终结者2"},
				  { "GameID":"28294","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_FinerReelsofLife.jpg","title":"好日子"},
				  { "GameID":"28246","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_TheLostPrincessAnastasia.jpg","title":"失落的阿纳斯塔西娅公主"},
				  { "GameID":"28232","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_TwistedCircus.jpg","title":"反转马戏团"},
				  { "GameID":"28226","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_ThunderstruckTwo1.jpg","title":"雷神2"},
				  { "GameID":"28222","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_TigerVsBear.jpg","title":"熊虎之战"},
				  { "GameID":"28218","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_TombRaider2.jpg","title":"古墓丽影"},
				  { "GameID":"28216","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_TombRaiderSotS1.jpg","title":"古墓丽影2"},
				  { "GameID":"28202","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_UntamedBengalTiger1.jpg","title":"野性的孟加拉虎"},
				  { "GameID":"28200","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_UntamedCrownedEagle.jpg","title":"狂野之鹰"},
				  { "GameID":"28190","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_UntamedWolfPack1.jpg","title":"野性的狼群"},
				  { "GameID":"28176","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_VictorianVillian.jpg","title":"维多利亚的恶棍"},
				  { "GameID":"28168","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_WasabiSan4.jpg","title":"芥末寿司"},
				  { "GameID":"28154","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_WhatonEarth1.jpg","title":"地球生物"},
				  { "GameID":"28146","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_WheelofWealthSE1.jpg","title":"财富转轮特别版"},
				  { "GameID":"28140","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_WhiteBuffalo.jpg","title":"白水牛"},
				  { "GameID":"50194","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_WildOrient_Button_ZH.jpg","title":"东方珍兽"},
				  { "GameID":"28126","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_WitchesWealth1.jpg","title":"女巫的财富"},
				  { "GameID":"28692","src":"http://image.beike188.com/POLY/mg_img/bonus_slot/BTN_AgeofDiscovery3.jpg","title":"大航海时代"}			  
               ], 

            'classic_slot':[ 
                  { "GameID":"28248","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_Belissimo17.jpg","title":"超级厨王"},
				  { "GameID":"28296","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_BreakDaBank1.jpg","title":"抢银行"},
				  { "GameID":"28354","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_CashClams2.jpg","title":"现金蚬"},
				  { "GameID":"28358","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_CashCrazy9.jpg","title":"财运疯狂"},
				  { "GameID":"28400","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_CoolBuck1.jpg","title":"酷巴克"},
				  { "GameID":"28408","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_CosmicCat1.jpg","title":"宇宙猫"},
				  { "GameID":"28414","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_CouchPotato2.jpg","title":"沙发土豆"},
				  { "GameID":"28510","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_DoubleMagic1.jpg","title":"双魔"},
				  { "GameID":"28514","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_DoubleWammy1.jpg","title":"双重韦密"},
				  { "GameID":"28582","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_FantasticSevens1.jpg","title":"奇妙7"},
				  { "GameID":"28588","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_FlyingAce2.jpg","title":"超级飞行员"},
				  { "GameID":"28594","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_FortuneCookie7.jpg","title":"幸运曲奇"},
				  { "GameID":"28604","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_FruitSlots1.jpg","title":"水果老虎机"},
				  { "GameID":"28624","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_GoldCoast3.jpg","title":"黄金海岸"},
				  { "GameID":"28628","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_GoldenDragon6.jpg","title":"黄金龙"},
				  { "GameID":"28490","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_HappyNewYear3.jpg","title":"新年快乐"},
				  { "GameID":"28558","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_JackpotExpress1.jpg","title":"累计奖金快车"},
				  { "GameID":"28654","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_JingleBells6.jpg","title":"铃儿响叮当"},
				  { "GameID":"28724","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_JurassicJackpot1.jpg","title":"侏罗纪大奖"},
				  { "GameID":"28786","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_Legacy2.jpg","title":"遗产L"},
				  { "GameID":"28482","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_RapidReels5.jpg","title":"急速转轮"},
				  { "GameID":"28438","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_RocktheBoat18.jpg","title":"摇滚船"},
				  { "GameID":"28430","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_RomanRiches11.jpg","title":"罗马财富"},
				  { "GameID":"28356","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_SpectacularWheelOfWealth1.jpg","title":"财富之轮"},
				  { "GameID":"28210","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_TripleMagic1.jpg","title":"三魔法"},
				  { "GameID":"28156","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_WheelOfWealth1.jpg","title":"水果财富"},
				  { "GameID":"29573","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_WinSpinner1.jpg","title":"钱来运转"},
				  { "GameID":"28124","src":"http://image.beike188.com/POLY/mg_img/classic_slot/BTN_ZanyZebra1.jpg","title":"燃尼巨蟒"}

            ],
			 'feature_slot':[  
				  { "GameID":"28138","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_AgentJaneBlonde7.jpg","title":"美女秘探"},
				  { "GameID":"28194","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_AvalonHD_ZH.jpg","title":"阿瓦隆"},
				  { "GameID":"28240","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_BattlestarGalactica1.jpg","title":"太空堡垒"},
				  { "GameID":"28292","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_BreakAway1.jpg","title":"冰球突破"},
				  { "GameID":"28404","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_CoolWolf1.jpg","title":"酷狼"},
				  { "GameID":"28568","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Elementals2.jpg","title":"水果怪兽"},
				  { "GameID":"28586","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_FishParty1.jpg","title":"派对鱼"},
				  { "GameID":"28606","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Galacticons.jpg","title":"银河舰队"},
				  { "GameID":"28626","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_GoldFactory.jpg","title":"黄金工厂"},
				  { "GameID":"28636","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_GoodToGo2.jpg","title":"疯狂赛道"},
				  { "GameID":"28664","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Harveys1.jpg","title":"哈维斯的晚餐"},
				  { "GameID":"28674","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Hohoho1.jpg","title":"嗬嗬嗬"},
				  { "GameID":"28540","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_HotInk1.jpg","title":"神奇墨水"},
				  { "GameID":"28734","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Kathmandu1.jpg","title":"卡萨缦都"},
				  { "GameID":"28776","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_LadiesNite5.jpg","title":"女仕之夜"},
				  { "GameID":"28774","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_LuckyWitch1.jpg","title":"幸运女巫"},
				  { "GameID":"28738","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_MayanPrincess1.jpg","title":"玛雅公主"},
				  { "GameID":"28666","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_MugshotMadness1.jpg","title":"疯狂假面"},
				  { "GameID":"28610","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Munchkins2.jpg","title":"怪兽曼琪肯"},
				  { "GameID":"28828","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Octopays.jpg","title":"章鱼"},
				  { "GameID":"28468","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_ReelGems1.jpg","title":"宝石迷阵"},
				  { "GameID":"28464","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_ReelStrike1.jpg","title":"卷行使价"},
				  { "GameID":"28458","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_RetroReels1.jpg","title":"复古旋转"},
				  { "GameID":"28456","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_RRExtreme1.jpg","title":"复古卷轴 - 极热"},
				  { "GameID":"28452","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_RRDiamondGlitz1.jpg","title":"复古卷轴钻石耀眼"},
				  { "GameID":"28450","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_RRHearts&Tarts1.jpg","title":"押韵的卷轴 - 心挞"},
				  { "GameID":"28444","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_RivieraRiches1.jpg","title":"海滨财富"},
				  { "GameID":"28410","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_SecretAdmirer1.jpg","title":"秘密崇拜者"},
				  { "GameID":"28396","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_SilverFang1.jpg","title":"银芳"},
				  { "GameID":"28348","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_SpringBreak2.jpg","title":"春假"},
				  { "GameID":"28308","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_TallyHo1.jpg","title":"泰利嗬"},
				  { "GameID":"28228","src":"http://image.beike188.com/POLY/mg_img/feature_slot/BTN_Thunderstruck1.jpg","title":"雷神"}			  

            ],
			 'others':[  
				  { "GameID":"28242","src":"http://image.beike188.com/POLY/mg_img/others/BTN_BeerFest1.jpg","title":"啤酒巨星"},
				  { "GameID":"28276","src":"http://image.beike188.com/POLY/mg_img/others/BTN_BingoBonanza1.jpg","title":"宾果富豪"},
				  { "GameID":"28278","src":"http://image.beike188.com/POLY/mg_img/others/BTN_BunnyBoiler1.jpg","title":"兔子锅炉"},
				  /*{ "GameID":"28290","src":"http://image.beike188.com/POLY/mg_img/others/","title":"击倒"},*/
				  { "GameID":"29591","src":"http://image.beike188.com/POLY/mg_img/others/BTN_BubbleBonanza.jpg","title":"泡泡富豪"},
				  { "GameID":"28330","src":"http://image.beike188.com/POLY/mg_img/others/BTN_BunnyBoilerGold1.jpg","title":"黄金兔子锅炉"},
				  { "GameID":"28372","src":"http://image.beike188.com/POLY/mg_img/others/BTN_Cashapillar1.jpg","title":"昆虫派对 "},
				  { "GameID":"28428","src":"http://image.beike188.com/POLY/mg_img/others/BTN_CrownAndAnchor1.jpg","title":"国际鱼虾蟹骰宝"},
				  { "GameID":"28432","src":"http://image.beike188.com/POLY/mg_img/others/BTN_CryptCrusade1.jpg","title":"地穴的远征"},
				  { "GameID":"28436","src":"http://image.beike188.com/POLY/mg_img/others/BTN_CryptCrusadeGold1.jpg","title":"黄金地穴的远征"},
				  { "GameID":"28448","src":"http://image.beike188.com/POLY/mg_img/others/BTN_DawnoftheBread1.jpg","title":"黎明的面包"},
				 /* { "GameID":"28524","src":"http://image.beike188.com/POLY/mg_img/others/","title":"龙的鸿运"},*/
				  { "GameID":"28566","src":"http://image.beike188.com/POLY/mg_img/others/BTN_ElectroBingo1.jpg","title":"电宾果"},
				  { "GameID":"28590","src":"http://image.beike188.com/POLY/mg_img/others/BTN_FoamyFortunes1.jpg","title":"泡沫财富"},
				  { "GameID":"28596","src":"http://image.beike188.com/POLY/mg_img/others/BTN_FourByFour1.jpg","title":"四乘四"},
				  { "GameID":"28598","src":"http://image.beike188.com/POLY/mg_img/others/BTN_FreezingFuzzballs1.jpg","title":"冻结模糊球"},
				  { "GameID":"28616","src":"http://image.beike188.com/POLY/mg_img/others/BTN_GameSetandScratch1.jpg","title":"网球最终局"},
				  { "GameID":"28614","src":"http://image.beike188.com/POLY/mg_img/others/BTN_Germinator1.jpg","title":"细菌对对碰"},
				  { "GameID":"28632","src":"http://image.beike188.com/POLY/mg_img/others/BTN_GoldenGhouls1.jpg","title":"黄金食尸鬼"},
				  { "GameID":"28640","src":"http://image.beike188.com/POLY/mg_img/others/BTN_GrannyPrix1.jpg","title":"老太太赛车"},
				  { "GameID":"28646","src":"http://image.beike188.com/POLY/mg_img/others/BTN_HairyFairies1.jpg","title":"毛茸茸的仙女"},
				  { "GameID":"28650","src":"http://image.beike188.com/POLY/mg_img/others/BTN_Halloweenies1.jpg","title":"万圣节"},
				  { "GameID":"28488","src":"http://image.beike188.com/POLY/mg_img/others/BTN_HandToHandCombat1.jpg","title":"肉搏战"},
				  { "GameID":"28504","src":"http://image.beike188.com/POLY/mg_img/others/BTN_Hexaline1.jpg","title":"六线"},
				  { "GameID":"29450","src":"http://image.beike188.com/POLY/mg_img/others/BTN_InstantWinCardSelector1.jpg","title":"刮刮卡20合一"},
				  { "GameID":"28740","src":"http://image.beike188.com/POLY/mg_img/others/BTN_Keno3.jpg","title":"基诺"},
				  { "GameID":"28778","src":"http://image.beike188.com/POLY/mg_img/others/BTN_LuckyNumbers1.jpg","title":"幸运数字"},
				  { "GameID":"28756","src":"http://image.beike188.com/POLY/mg_img/others/BTN_MaxDamage1.jpg","title":"星战传奇"},
				  { "GameID":"28748","src":"http://image.beike188.com/POLY/mg_img/others/BTN_MayanBingo1.jpg","title":"玛雅宾果"},
				  { "GameID":"66084","src":"http://image.beike188.com/POLY/mg_img/others/BTN_MonkeyKeno_ZH.jpg","title":"猴子基诺"},
				  { "GameID":"28612","src":"http://image.beike188.com/POLY/mg_img/others/BTN_MumbaiMagic1.jpg","title":"孟买魔术"},
				  { "GameID":"28658","src":"http://image.beike188.com/POLY/mg_img/others/BTN_OffsideandSeek1.jpg","title":"临门一脚"},
				  { "GameID":"28550","src":"http://image.beike188.com/POLY/mg_img/others/BTN_PharaohBingo1.jpg","title":"法老宾果"},
				  { "GameID":"28842","src":"http://image.beike188.com/POLY/mg_img/others/BTN_PharoahsGems1.jpg","title":"隔离的宝石"},
				  { "GameID":"28544","src":"http://image.beike188.com/POLY/mg_img/others/BTN_PlundertheSea1.jpg","title":"掠夺之海"},
				  { "GameID":"28530","src":"http://image.beike188.com/POLY/mg_img/others/BTN_PremierRacing1.jpg","title":"超级赛马"},
				  { "GameID":"28904","src":"http://image.beike188.com/POLY/mg_img/others/BTN_PremierTrotting1.jpg","title":"超级马车赛"},
				  { "GameID":"28420","src":"http://image.beike188.com/POLY/mg_img/others/BTN_SambaBingo1.jpg","title":"萨巴宾果"},
				  { "GameID":"28394","src":"http://image.beike188.com/POLY/mg_img/others/BTN_SixShooterLooterGold1.jpg","title":"六位枪手掠夺者黄金版"},
				  { "GameID":"28390","src":"http://image.beike188.com/POLY/mg_img/others/BTN_SlamFunk1.jpg","title":"猛撞恐惧"},
				  { "GameID":"28370","src":"http://image.beike188.com/POLY/mg_img/others/BTN_SpaceEvader1.jpg","title":"太空逃避物"},
				  { "GameID":"28366","src":"http://image.beike188.com/POLY/mg_img/others/BTN_SpaceEvaderGold1.jpg","title":"太空逃避物黄金版"},
				  { "GameID":"28352","src":"http://image.beike188.com/POLY/mg_img/others/BTN_Spingo.jpg","title":"我推"},
				  { "GameID":"28322","src":"http://image.beike188.com/POLY/mg_img/others/BTN_SuperBonusBingo1.jpg","title":"超级奖金宾果"},
				  { "GameID":"28318","src":"http://image.beike188.com/POLY/mg_img/others/BTN_SuperZeroes1.jpg","title":"超级零点"},
				  { "GameID":"28212","src":"http://image.beike188.com/POLY/mg_img/others/BTN_Triangulation.jpg","title":"三角"},
				  { "GameID":"28206","src":"http://image.beike188.com/POLY/mg_img/others/BTN_TurtleyAwesome1.jpg","title":"棒棒乌龟"},
				  { "GameID":"28158","src":"http://image.beike188.com/POLY/mg_img/others/BTN_WhackaJackpot1.jpg","title":"瓜分大奖"},
				  { "GameID":"28132","src":"http://image.beike188.com/POLY/mg_img/others/BTN_WildChampions1.jpg","title":"野生冠军"}

            ],
			 'table':[  
				  { "GameID":"28204","src":"http://image.beike188.com/POLY/mg_img/table/BTN_USRoulette1.jpg","title":"美式轮盘"},
				  { "GameID":"28192","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_AtlanticCityBlackjack1.jpg","title":"大西洋城黄金21点"},
				  { "GameID":"28234","src":"http://image.beike188.com/POLY/mg_img/table/BTN_Baccarat2.jpg","title":"百家乐"},
				  { "GameID":"28236","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_Baccarat1.jpg","title":"百家乐黄金版"},
				  { "GameID":"28260","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_BigFive1.jpg","title":"大五黄金21点"},
				  { "GameID":"28398","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_ClassicBlackjack1.jpg","title":"经典黄金21点"},
				  { "GameID":"28442","src":"http://image.beike188.com/POLY/mg_img/table/BTN_Cyberstud1.jpg","title":"网络扑克"},
				  { "GameID":"28494","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_DoubleExposureBlackjack1.jpg","title":"双重黄金曝光"},
				  { "GameID":"28576","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_EuroBlackjack1.jpg","title":"欧洲黄金21点"},
				  { "GameID":"28580","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_EuroRoulette1.jpg","title":"欧式黄金轮盘"},
				  { "GameID":"28602","src":"http://image.beike188.com/POLY/mg_img/table/BTN_FrenchRoulette1.jpg","title":"法式轮盘"},
				  { "GameID":"28508","src":"http://image.beike188.com/POLY/mg_img/table/BTN_HighLimitBaccarat1.jpg","title":"高限制百家乐"},
				  { "GameID":"28668","src":"http://image.beike188.com/POLY/mg_img/table/BTN_EuroBlackjackHighLimit1.jpg","title":"欧式高限21点"},
				  { "GameID":"28518","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_MHHighSpeedPoker1.jpg","title":"高速扑克"},
				  { "GameID":"28520","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_HiLo13EuroBJ1.jpg","title":"13欧洲 21点黃金桌"},
				  { "GameID":"28816","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_MultiWheelRoulette1.jpg","title":"复式黄金轮盘"},
				  { "GameID":"28820","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_MHEuroBlackjack2.jpg","title":"多手21点黄金桌"},
				  { "GameID":"28822","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_MHPerfectPairsBlackjack1.jpg","title":"多手21点黄金桌"},
				  { "GameID":"28678","src":"http://image.beike188.com/POLY/mg_img/table/BTN_MHPremierBlackjack1.jpg","title":"多手21点黄金桌"},
				  { "GameID":"28826","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_MHVegasDowntown2.jpg","title":"多手21点黄金桌"},
				  { "GameID":"28538","src":"http://image.beike188.com/POLY/mg_img/table/BTN_PremierBlackjackHiLo1.jpg","title":"21点黄金桌"},
				  { "GameID":"28536","src":"http://image.beike188.com/POLY/mg_img/table/BTN_PremierBlackjackHiStreak1.jpg","title":"21点黄金桌"},
				  { "GameID":"28532","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_MHBonusBlackjack2.jpg","title":"多手21点黄金桌"},
				  { "GameID":"28528","src":"http://image.beike188.com/POLY/mg_img/table/BTN_PremierRoulette9.jpg","title":"轮盘"},
				  { "GameID":"28526","src":"http://image.beike188.com/POLY/mg_img/table/BTN_PremierRouletteDE1.jpg","title":"轮盘钻石版"},
				  { "GameID":"28362","src":"http://image.beike188.com/POLY/mg_img/table/BTN_SpanishBlackjack1.jpg","title":"西班牙21点"},
				  { "GameID":"28360","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_SpanishBlackjack1.jpg","title":"西班牙21点"},
				  { "GameID":"28320","src":"http://image.beike188.com/POLY/mg_img/table/BTN_SuperFun21Blackjack1.jpg","title":"超级有趣21"},
				 /* { "GameID":"28208","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_TriplePocket1.jpg","title":"三人德州扑克"},*/
				  { "GameID":"28186","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_VegasSingleDeck1.jpg","title":"拉斯维加斯21点单人黄金桌"},
				  { "GameID":"28180","src":"http://image.beike188.com/POLY/mg_img/table/BTN_VegasStripBlackjack1.jpg","title":"拉斯维加斯21点"},
				  { "GameID":"28184","src":"http://image.beike188.com/POLY/mg_img/table/BTN_GoldSeries_VegasStrip1.jpg","title":"拉斯维加斯21点黄金桌"}			  

            ],
			 'video_poker':[  
				  { "GameID":"28116","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_AcesAndEights1.jpg","title":"王牌和八分"},
				  { "GameID":"28122","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_AcesFacesPowerPoker1.jpg","title":"王牌和面孔"},
				  { "GameID":"28128","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_AcesFaces1.jpg","title":"王牌和面孔"},
				  { "GameID":"28150","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_AllAces1.jpg","title":"所有王牌扑克"},
				  { "GameID":"28152","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_AllAmerican1.jpg","title":"所有美国"},
				  { "GameID":"28280","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_BonusDeucesWild1.jpg","title":"疯狂奖金局末平分"},
				  { "GameID":"28282","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_BonusDeucesWild1.jpg","title":"奖金扑克"},
				  { "GameID":"28284","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_BonusPokerDeluxe1.jpg","title":"豪华奖金扑克"},
				  { "GameID":"28460","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_DeucesJokerPowerPoker1.jpg","title":"百搭小丑扑克"},
				  { "GameID":"28466","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_DeucesJoker1.jpg","title":"百搭小丑扑克"},
				  { "GameID":"28470","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_DeucesWildPowerPoker1.jpg","title":"万能两点"},
				  { "GameID":"28486","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_DoubleBonus1.jpg","title":"双重奖金扑克"},
				  { "GameID":"28492","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_DoubleDoubleBonus1.jpg","title":"换牌扑克"},
				  { "GameID":"28498","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_DoubleJokerPowerPoker1.jpg","title":"双百搭"},
				  { "GameID":"28506","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_DoubleJoker1.jpg","title":"双百搭"},
				  { "GameID":"28686","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_JacksorBetterPowerPoker1.jpg","title":"千斤顶或更好"},
				  { "GameID":"28694","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_JacksOrBetter1.jpg","title":"千斤顶或更好"},
				  { "GameID":"28710","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_JokerPokerPowerPoker1.jpg","title":"小丑扑克"},
				  { "GameID":"28720","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_JokerPoker1.jpg","title":"小丑扑克"},
				  { "GameID":"28814","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_LouisianaDouble1.jpg","title":"路易斯安那双"},
				  { "GameID":"28874","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_PokerPursuit1.jpg","title":"扑克追求"},
				  { "GameID":"28302","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_TensOrBetter1.jpg","title":"数万或更好"},
				  { "GameID":"28304","src":"http://image.beike188.com/POLY/mg_img/video_poker/BTN_TensOrBetterPowerPoker1.jpg","title":"数万或更好"}

            ],
			 'video_slot':[  
				  { "GameID":"69184","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Classic243.jpg","title":"经典 243"},
				  { "GameID":"69012","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_SecretRomance_ZH.jpg","title":"秘密爱慕者"},
				  { "GameID":"68994","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_FruitVsCandy_ZH.jpg","title":"水果VS糖果"},
				  { "GameID":"28114","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_5ReelDrive1.jpg","title":"5卷的驱动器"},
				  { "GameID":"28134","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_AdventurePalaceHD.jpg","title":"宫廷历险"},
				  { "GameID":"28144","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_AlaskanFishing1.jpg","title":"阿拉斯加钓鱼"},
				  { "GameID":"28174","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Ariana_ZH.jpg","title":"爱丽娜"},
				  { "GameID":"28188","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_AsianBeauty1.jpg","title":"亚洲美人"},
				  { "GameID":"44751","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_BasketballStar_ZH.jpg","title":"篮球巨星"},
				  { "GameID":"28268","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_BigChef_ZH.jpg","title":"厨神"},
				  { "GameID":"28272","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_BigKahuna_SL1.jpg","title":"征服钱海-蛇与梯子"},
				  { "GameID":"28274","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_BigTop1.jpg","title":"马戏篷"},
				  { "GameID":"28310","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_BreakDaBankAgain1.jpg","title":"银行爆破"},
				  { "GameID":"28332","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_BurningDesire1.jpg","title":"燃烧的欲望"},
				  { "GameID":"28350","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Carnaval2.jpg","title":"狂欢节"},
				  { "GameID":"28368","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Cashapillar1.jpg","title":"昆虫派对"},
				  { "GameID":"28380","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_CentreCourt1.jpg","title":"中心球场"},
				  { "GameID":"28384","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_ChainMail_ZH.jpg","title":"锁子甲"},
				  { "GameID":"28418","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Crazy80s4.jpg","title":"疯狂的80年代"},
				  { "GameID":"28422","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_CrazyChameleons1.jpg","title":"疯狂的变色龙"},
				  { "GameID":"29561","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_CricketStar.jpg","title":"板球明星"},
				  { "GameID":"28424","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Crocodopolis.jpg","title":"鳄鱼建城邦"},
				  { "GameID":"28454","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_DeckTheHalls1.jpg","title":"闪亮的圣诞节 ？"},
				  { "GameID":"28478","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_DrLove.jpg","title":"医生的爱"},
				  { "GameID":"67413","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Dragonz_en.jpg","title":"幸运龙宝贝"},
				  { "GameID":"28572","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_EnchantedWoods1.jpg","title":"魔法森林"},
				  { "GameID":"28584","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_FatLadySings1.jpg","title":"胖女人辛斯"},
				  { "GameID":"28608","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_GeniesGems2.jpg","title":"精灵宝石"},
				  { "GameID":"28630","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_GoldenEra.jpg","title":"黄金时代"},
				  { "GameID":"28634","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_GoldenPrincess.jpg","title":"黄金公主"},
				  { "GameID":"28638","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_GopherGold2.jpg","title":"黄金囊地鼠"},
				  { "GameID":"28642","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_GreatGriffin1.jpg","title":"大狮鹫"},
				  { "GameID":"45397","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_HappyHolidays_ZH.jpg","title":"快乐假日"},
				  { "GameID":"28574","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_HotAsHades_ZH.jpg","title":"地府烈焰"},
				  /*{ "GameID":"28534","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_HotShot3.jpg","title":"棒球直击"},*/
				  { "GameID":"28644","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_HoundHotel_ZH.jpg","title":"酷犬酒店"},
				  { "GameID":"68501","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Huangdi_TheYellowEmperor_zh.jpg","title":"轩辕帝传"},
				  { "GameID":"28548","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_ImmortalRomance1.jpg","title":"不朽的爱情"},
				  { "GameID":"28552","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_IrishEyes.jpg","title":"爱尔兰眼睛"},
				  { "GameID":"66481","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Junglejim_zh.jpg","title":"丛林吉姆-黄金国"},
				  { "GameID":"65978","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_KaraokeParty_ZH.jpg","title":"K歌乐韵"},
				  { "GameID":"28726","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_KaratePig1.jpg","title":"功夫小胖猪"},
				  { "GameID":"28762","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_KingsofCash1.jpg","title":"现金之王"},
				  { "GameID":"28772","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_KittyCabana_ZH.jpg","title":"凯蒂卡巴拉"},
				  { "GameID":"28812","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_LadyInRed2.jpg","title":"红衣女郎"},
				  { "GameID":"68527","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_LifeOfRiches_zh.jpg","title":"富裕人生"},
				  { "GameID":"66914","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_LostVegas_zh.jpg","title":"迷失拉斯维加斯"},
				  { "GameID":"28800","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_LuckyFirecracker.jpg","title":"招财鞭炮"},
				  { "GameID":"28788","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_LuckyLeprechaun.jpg","title":"幸运的小妖精"},
				  { "GameID":"42981","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_luckyTwins_ZH.jpg","title":"幸运双星"},
				  { "GameID":"28770","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_LuckyZodiac_ZH.jpg","title":"幸运生肖"},
				  { "GameID":"28758","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_MaxDamageSlot.jpg","title":"终极破坏"},
				  { "GameID":"28706","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_BreakdaBankAgainMegaSpin1.jpg","title":"银行爆破"},
				  { "GameID":"28696","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_MonsterMania1.jpg","title":"怪物躁狂症"},
				  { "GameID":"28564","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_OrientalFortune2.jpg","title":"东方财富"},
				  { "GameID":"42979","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_PeekABoo_ZH.jpg","title":"躲猫猫"},
				  { "GameID":"28546","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Pistoleras_ZH.jpg","title":"持枪王者"},
				  { "GameID":"28512","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_PurePlatinum1.jpg","title":"纯铂"},
				  { "GameID":"28912","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_RabbitintheHat.jpg","title":"帽子里的兔子"},
				  { "GameID":"28916","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_RammessesRiches.jpg","title":"拉美西斯的财富"},
				  { "GameID":"28474","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_RedHotDevil.jpg","title":"红唇诱惑"},
				  { "GameID":"61495","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_ReelSpinner_zh.jpg","title":"旋转大战"},
				  { "GameID":"28462","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_ReelThunder2.jpg","title":"雷电击"},
				  { "GameID":"28446","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_RRKing1.jpg","title":"押韵的卷轴 - 老国王科尔"},
				  { "GameID":"28426","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_RugbyStar_ZH.jpg","title":"橄榄球明星"},
				  { "GameID":"28412","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Scrooge1.jpg","title":"守财奴"},
				  { "GameID":"45399","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Serenity_ZH.jpg","title":"宁静"},
				  { "GameID":"28388","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_somanymonsters.jpg","title":"怪兽多多"},
				  { "GameID":"28386","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_somuchcandy.jpg","title":"糖果多多"},
				  { "GameID":"28382","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_somuchsushi.jpg","title":"寿司多多"},
				  { "GameID":"45401","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_StarDust_ZH.jpg","title":"星尘"},
				  { "GameID":"28340","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_StashoftheTitans1.jpg","title":"泰坦之藏匿"},
				  { "GameID":"42267","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_summertime.jpg","title":"夏天"},
				  { "GameID":"28328","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_SunQuest3.jpg","title":"探索太阳"},
				  { "GameID":"28326","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_SupeItUp2.jpg","title":"跑起来"},
				  { "GameID":"28312","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_SweetHarvest1.jpg","title":"甜蜜的收获"},
				 /* { "GameID":"67812","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_Tarzan_Button_en.jpg","title":"泰山"},*/
				  { "GameID":"28238","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_RatPack1.jpg","title":"鼠包"},
				  { "GameID":"28230","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_ThroneOfEgypt1.jpg","title":"埃及王座"},
				  { "GameID":"28112","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_TitansOfTheSun_Hyperion_ZH.jpg","title":"太阳神之许珀里翁"},
				  { "GameID":"28220","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_TitansOfTheSun_Theia_ZH.jpg","title":"太阳神之忒伊亚"},
				  { "GameID":"28214","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_TotemTreasure1.jpg","title":"图腾宝藏"},
				  { "GameID":"28196","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_UntamedGiantPanda.jpg","title":"大熊猫"},
				  { "GameID":"28172","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_VinylCountdown4.jpg","title":"乙烯基倒计时"},
				  { "GameID":"28178","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_WhataHoot3.jpg","title":"猫头鹰乐园"},
				  { "GameID":"28142","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_WildCatch.jpg","title":"野生捕鱼"},
				  { "GameID":"61499","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_winsumdimsum_zh.jpg","title":"开心点心"},
				  { "GameID":"28130","src":"http://image.beike188.com/POLY/mg_img/video_slot/BTN_WinningWizards1.jpg","title":"赢得向导"}
            ]
			
         }